# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_Authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authorization(object):
    def setupUi(self, Authorization):
        Authorization.setObjectName("Authorization")
        Authorization.resize(333, 352)
        Authorization.setMinimumSize(QtCore.QSize(333, 352))
        Authorization.setMaximumSize(QtCore.QSize(333, 352))
        Authorization.setStyleSheet("background-color: rgb(64, 57, 101);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Authorization)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(70, 64, 98);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_remove = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_remove.setFont(font)
        self.btn_remove.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_remove.setMouseTracking(True)
        self.btn_remove.setTabletTracking(True)
        self.btn_remove.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/remove.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(90, 80, 120);\n"
"}")
        self.btn_remove.setText("")
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        self.btn_close = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/close.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("image: url(GUI/icons/KFU_WHITE.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.login = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setMaximumSize(QtCore.QSize(16777215, 35))
        self.login.setStyleSheet("border: transparent;\n"
"background-color: rgb(70, 64, 98);\n"
"color: rgba(255, 255, 255,1);\n"
"border: 2px solid rgba(62, 63, 70, 0);\n"
"border-radius: 12px;")
        self.login.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.login.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.login.setObjectName("login")
        self.verticalLayout_3.addWidget(self.login)
        self.password = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setMaximumSize(QtCore.QSize(16777215, 35))
        self.password.setStyleSheet("border: transparent;\n"
"background-color: rgb(70, 64, 98);\n"
"color: rgba(255, 255, 255,1);\n"
"border: 2px solid rgba(62, 63, 70, 0);\n"
"border-radius: 12px;")
        self.password.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.password.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.password.setObjectName("password")
        self.verticalLayout_3.addWidget(self.password)
        self.verticalLayout_2.addWidget(self.frame)
        self.notif_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.notif_label.setFont(font)
        self.notif_label.setText("")
        self.notif_label.setAlignment(QtCore.Qt.AlignCenter)
        self.notif_label.setObjectName("notif_label")
        self.verticalLayout_2.addWidget(self.notif_label)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_in = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_in.sizePolicy().hasHeightForWidth())
        self.btn_in.setSizePolicy(sizePolicy)
        self.btn_in.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_in.setFont(font)
        self.btn_in.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_in.setStyleSheet("QPushButton {\n"
"    border: 2px;\n"
"    background-color: rgb(54, 50, 87);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(70, 65, 100);\n"
"}")
        self.btn_in.setObjectName("btn_in")
        self.horizontalLayout_2.addWidget(self.btn_in)
        self.btn_reg = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reg.sizePolicy().hasHeightForWidth())
        self.btn_reg.setSizePolicy(sizePolicy)
        self.btn_reg.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_reg.setFont(font)
        self.btn_reg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reg.setStyleSheet("QPushButton {\n"
"    border: 2px;\n"
"    background-color: rgb(54, 50, 87);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(70, 65, 100);\n"
"}")
        self.btn_reg.setObjectName("btn_reg")
        self.horizontalLayout_2.addWidget(self.btn_reg)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.widget_2)
        Authorization.setCentralWidget(self.centralwidget)

        self.retranslateUi(Authorization)
        QtCore.QMetaObject.connectSlotsByName(Authorization)

    def retranslateUi(self, Authorization):
        _translate = QtCore.QCoreApplication.translate
        Authorization.setWindowTitle(_translate("Authorization", "Авторизация"))
        self.login.setPlaceholderText(_translate("Authorization", "Логин"))
        self.password.setPlaceholderText(_translate("Authorization", "Пароль"))
        self.btn_in.setText(_translate("Authorization", "Войти"))
        self.btn_reg.setText(_translate("Authorization", "Регистрация"))
