# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(70, 64, 98);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_btn = QtWidgets.QWidget(self.widget)
        self.widget_btn.setObjectName("widget_btn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_btn)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_remove = QtWidgets.QPushButton(self.widget_btn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_remove.setFont(font)
        self.btn_remove.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_remove.setMouseTracking(True)
        self.btn_remove.setTabletTracking(True)
        self.btn_remove.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/remove.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(90, 80, 120);\n"
"}")
        self.btn_remove.setText("")
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        self.btn_shape = QtWidgets.QPushButton(self.widget_btn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_shape.setFont(font)
        self.btn_shape.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/check_box.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(90, 80, 120);\n"
"}")
        self.btn_shape.setText("")
        self.btn_shape.setObjectName("btn_shape")
        self.horizontalLayout.addWidget(self.btn_shape)
        self.btn_close = QtWidgets.QPushButton(self.widget_btn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/close.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_2.addWidget(self.widget_btn, 0, QtCore.Qt.AlignTop)
        self.widget_main = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_main.sizePolicy().hasHeightForWidth())
        self.widget_main.setSizePolicy(sizePolicy)
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QCustomSlideMenu(self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)
        self.verticalLayout_9.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_9.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_left_main = QtWidgets.QWidget(self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left_main.sizePolicy().hasHeightForWidth())
        self.widget_left_main.setSizePolicy(sizePolicy)
        self.widget_left_main.setStyleSheet("background-color: rgb(54, 50, 87);")
        self.widget_left_main.setObjectName("widget_left_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_left_main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_settings = QtWidgets.QWidget(self.widget_left_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_settings.sizePolicy().hasHeightForWidth())
        self.widget_settings.setSizePolicy(sizePolicy)
        self.widget_settings.setObjectName("widget_settings")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_settings)
        self.horizontalLayout_3.setContentsMargins(0, 6, 10, 6)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_settings = QtWidgets.QPushButton(self.widget_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_settings.setFont(font)
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/menu.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(70, 65, 100);\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setIconSize(QtCore.QSize(16, 16))
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_3.addWidget(self.btn_settings, 0, QtCore.Qt.AlignLeft)
        self.search_text = QtWidgets.QTextEdit(self.widget_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_text.sizePolicy().hasHeightForWidth())
        self.search_text.setSizePolicy(sizePolicy)
        self.search_text.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_text.setAcceptDrops(False)
        self.search_text.setStyleSheet("background-color: rgb(70, 64, 98);\n"
"color: rgba(255, 255, 255,1);\n"
"border: 2px solid rgba(62, 63, 70, 0);\n"
"border-radius: 12px;")
        self.search_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.search_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.search_text.setTabChangesFocus(True)
        self.search_text.setOverwriteMode(False)
        self.search_text.setAcceptRichText(True)
        self.search_text.setObjectName("search_text")
        self.horizontalLayout_3.addWidget(self.search_text)
        self.verticalLayout_3.addWidget(self.widget_settings)
        self.widget_users_list = QtWidgets.QWidget(self.widget_left_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_users_list.sizePolicy().hasHeightForWidth())
        self.widget_users_list.setSizePolicy(sizePolicy)
        self.widget_users_list.setObjectName("widget_users_list")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_users_list)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.list_users = QtWidgets.QListWidget(self.widget_users_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_users.sizePolicy().hasHeightForWidth())
        self.list_users.setSizePolicy(sizePolicy)
        self.list_users.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: transparent;")
        self.list_users.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_users.setObjectName("list_users")
        self.verticalLayout_7.addWidget(self.list_users, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.widget_users_list)
        self.horizontalLayout_2.addWidget(self.widget_left_main, 0, QtCore.Qt.AlignLeft)
        self.widget_right_main = QtWidgets.QWidget(self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_right_main.sizePolicy().hasHeightForWidth())
        self.widget_right_main.setSizePolicy(sizePolicy)
        self.widget_right_main.setObjectName("widget_right_main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_right_main)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_user = QtWidgets.QWidget(self.widget_right_main)
        self.widget_user.setStyleSheet("background-color: rgb(54, 50, 87);")
        self.widget_user.setObjectName("widget_user")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_user)
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, 16)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.user_label = QtWidgets.QLabel(self.widget_user)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_label.sizePolicy().hasHeightForWidth())
        self.user_label.setSizePolicy(sizePolicy)
        self.user_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.user_label.setText("")
        self.user_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_label.setObjectName("user_label")
        self.verticalLayout_5.addWidget(self.user_label)
        self.verticalLayout_4.addWidget(self.widget_user)
        self.stackedWidget_sms = QtWidgets.QStackedWidget(self.widget_right_main)
        self.stackedWidget_sms.setObjectName("stackedWidget_sms")
        self.stackedWidget_smsPage1 = QtWidgets.QWidget()
        self.stackedWidget_smsPage1.setObjectName("stackedWidget_smsPage1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stackedWidget_smsPage1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.stackedWidget_smsPage1)
        self.scrollArea.setStyleSheet("border: 1px solid transparent; /* Установка прозрачной границы */\n"
"    background-color: rgb(64, 57, 101);\n"
"    color: rgb(255, 255, 255);\n"
"QScrollArea {\n"
"    border: 1px solid transparent; /* Установка прозрачной границы */\n"
"    background-color: rgb(64, 57, 101);\n"
"    color: rgb(255, 255, 255);\n"
"    wight: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"background: #2f2f2f;\n"
"width: 15px;\n"
"margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"background: #5b5b5b;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"height: 0px;\n"
"}\n"
"")
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 306, 540))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sms_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sms_label.sizePolicy().hasHeightForWidth())
        self.sms_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sms_label.setFont(font)
        self.sms_label.setStyleSheet("background-color: rgb(64, 57, 101);\n"
"color: rgb(255, 255, 255);")
        self.sms_label.setText("")
        self.sms_label.setTextFormat(QtCore.Qt.AutoText)
        self.sms_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.sms_label.setObjectName("sms_label")
        self.horizontalLayout_5.addWidget(self.sms_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.stackedWidget_sms.addWidget(self.stackedWidget_smsPage1)
        self.page_info = QtWidgets.QWidget()
        self.page_info.setStyleSheet("background-color: rgb(64, 57, 101);\n"
"color: rgb(255, 255, 255);")
        self.page_info.setObjectName("page_info")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_info)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.page_info)
        self.label.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label.setStyleSheet("background-color: rgb(64, 57, 101);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.stackedWidget_sms.addWidget(self.page_info)
        self.verticalLayout_4.addWidget(self.stackedWidget_sms)
        self.widget_send_text = QtWidgets.QWidget(self.widget_right_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_send_text.sizePolicy().hasHeightForWidth())
        self.widget_send_text.setSizePolicy(sizePolicy)
        self.widget_send_text.setObjectName("widget_send_text")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_send_text)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.send_text = QtWidgets.QTextEdit(self.widget_send_text)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_text.sizePolicy().hasHeightForWidth())
        self.send_text.setSizePolicy(sizePolicy)
        self.send_text.setStyleSheet("color: rgba(255, 255, 255,1);\n"
"border: transparent;")
        self.send_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.send_text.setAcceptRichText(False)
        self.send_text.setObjectName("send_text")
        self.horizontalLayout_4.addWidget(self.send_text)
        self.btn_send = QtWidgets.QPushButton(self.widget_send_text)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_send.setFont(font)
        self.btn_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_send.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/send.png);\n"
"}\n"
"")
        self.btn_send.setText("")
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_4.addWidget(self.btn_send)
        self.verticalLayout_4.addWidget(self.widget_send_text, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.widget_right_main)
        self.verticalLayout_2.addWidget(self.widget_main)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_sms.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Месседжер"))
        self.label_2.setText(_translate("MainWindow", "icon"))
        self.label_3.setText(_translate("MainWindow", "user name"))
        self.pushButton.setText(_translate("MainWindow", "Настройки "))
        self.pushButton_2.setText(_translate("MainWindow", "Выйти"))
        self.label_4.setText(_translate("MainWindow", "info"))
        self.search_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>"))
        self.search_text.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Выберите, кому хотели бы написать"))
        self.send_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>"))
        self.send_text.setPlaceholderText(_translate("MainWindow", "Введите сообщение..."))
        self.btn_send.setShortcut(_translate("MainWindow", "Return"))
from Custom_Widgets.QCustomSlideMenu import QCustomSlideMenu
