# Form implementation generated from reading ui file '.\UI_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(70, 64, 98);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_btn = QtWidgets.QWidget(parent=self.widget)
        self.widget_btn.setObjectName("widget_btn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_btn)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_remove = QtWidgets.QPushButton(parent=self.widget_btn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_remove.setFont(font)
        self.btn_remove.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.btn_remove.setMouseTracking(True)
        self.btn_remove.setTabletTracking(True)
        self.btn_remove.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/remove.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(90, 80, 120);\n"
"}")
        self.btn_remove.setText("")
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        self.btn_shape = QtWidgets.QPushButton(parent=self.widget_btn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_shape.setFont(font)
        self.btn_shape.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/check_box.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(90, 80, 120);\n"
"}")
        self.btn_shape.setText("")
        self.btn_shape.setObjectName("btn_shape")
        self.horizontalLayout.addWidget(self.btn_shape)
        self.btn_close = QtWidgets.QPushButton(parent=self.widget_btn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/close.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_2.addWidget(self.widget_btn, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_main = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_main.sizePolicy().hasHeightForWidth())
        self.widget_main.setSizePolicy(sizePolicy)
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_left_main = QtWidgets.QWidget(parent=self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left_main.sizePolicy().hasHeightForWidth())
        self.widget_left_main.setSizePolicy(sizePolicy)
        self.widget_left_main.setStyleSheet("background-color: rgb(54, 50, 87);")
        self.widget_left_main.setObjectName("widget_left_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_left_main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_settings = QtWidgets.QWidget(parent=self.widget_left_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_settings.sizePolicy().hasHeightForWidth())
        self.widget_settings.setSizePolicy(sizePolicy)
        self.widget_settings.setObjectName("widget_settings")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_settings)
        self.horizontalLayout_3.setContentsMargins(0, 6, 10, 6)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_settings = QtWidgets.QPushButton(parent=self.widget_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_settings.setFont(font)
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/menu.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(70, 65, 100);\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setIconSize(QtCore.QSize(16, 16))
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_3.addWidget(self.btn_settings, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.search_text = QtWidgets.QTextEdit(parent=self.widget_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_text.sizePolicy().hasHeightForWidth())
        self.search_text.setSizePolicy(sizePolicy)
        self.search_text.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_text.setAcceptDrops(False)
        self.search_text.setStyleSheet("background-color: rgb(70, 64, 98);\n"
"color: rgba(255, 255, 255,1);\n"
"border: 2px solid rgba(62, 63, 70, 0);\n"
"border-radius: 12px;")
        self.search_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.search_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.search_text.setTabChangesFocus(True)
        self.search_text.setOverwriteMode(False)
        self.search_text.setAcceptRichText(True)
        self.search_text.setObjectName("search_text")
        self.horizontalLayout_3.addWidget(self.search_text)
        self.verticalLayout_3.addWidget(self.widget_settings)
        self.widget_users_list = QtWidgets.QWidget(parent=self.widget_left_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_users_list.sizePolicy().hasHeightForWidth())
        self.widget_users_list.setSizePolicy(sizePolicy)
        self.widget_users_list.setObjectName("widget_users_list")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_users_list)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.list_users = QtWidgets.QListWidget(parent=self.widget_users_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_users.sizePolicy().hasHeightForWidth())
        self.list_users.setSizePolicy(sizePolicy)
        self.list_users.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: transparent;")
        self.list_users.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.list_users.setObjectName("list_users")
        self.verticalLayout_7.addWidget(self.list_users, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_3.addWidget(self.widget_users_list)
        self.horizontalLayout_2.addWidget(self.widget_left_main, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_right_main = QtWidgets.QWidget(parent=self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_right_main.sizePolicy().hasHeightForWidth())
        self.widget_right_main.setSizePolicy(sizePolicy)
        self.widget_right_main.setObjectName("widget_right_main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_right_main)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_user = QtWidgets.QWidget(parent=self.widget_right_main)
        self.widget_user.setStyleSheet("background-color: rgb(54, 50, 87);")
        self.widget_user.setObjectName("widget_user")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_user)
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, 16)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.user_label = QtWidgets.QLabel(parent=self.widget_user)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_label.sizePolicy().hasHeightForWidth())
        self.user_label.setSizePolicy(sizePolicy)
        self.user_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.user_label.setText("")
        self.user_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.user_label.setObjectName("user_label")
        self.verticalLayout_5.addWidget(self.user_label)
        self.verticalLayout_4.addWidget(self.widget_user)
        self.widget_sms = QtWidgets.QWidget(parent=self.widget_right_main)
        self.widget_sms.setObjectName("widget_sms")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_sms)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sms_label = QtWidgets.QLabel(parent=self.widget_sms)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sms_label.sizePolicy().hasHeightForWidth())
        self.sms_label.setSizePolicy(sizePolicy)
        self.sms_label.setStyleSheet("background-color: rgb(64, 57, 101);\n"
"color: rgb(255, 255, 255);")
        self.sms_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sms_label.setObjectName("sms_label")
        self.verticalLayout_6.addWidget(self.sms_label)
        self.verticalLayout_4.addWidget(self.widget_sms)
        self.widget_send_text = QtWidgets.QWidget(parent=self.widget_right_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_send_text.sizePolicy().hasHeightForWidth())
        self.widget_send_text.setSizePolicy(sizePolicy)
        self.widget_send_text.setObjectName("widget_send_text")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_send_text)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.send_text = QtWidgets.QTextEdit(parent=self.widget_send_text)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_text.sizePolicy().hasHeightForWidth())
        self.send_text.setSizePolicy(sizePolicy)
        self.send_text.setStyleSheet("color: rgba(255, 255, 255,1);\n"
"border: transparent;")
        self.send_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.send_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.send_text.setObjectName("send_text")
        self.horizontalLayout_4.addWidget(self.send_text)
        self.btn_send = QtWidgets.QPushButton(parent=self.widget_send_text)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_send.setFont(font)
        self.btn_send.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_send.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgba(62, 63, 70, 0);\n"
"    border-radius: 0px;\n"
"    image: url(GUI/icons/send.png);\n"
"}\n"
"")
        self.btn_send.setText("")
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_4.addWidget(self.btn_send)
        self.verticalLayout_4.addWidget(self.widget_send_text, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_2.addWidget(self.widget_right_main)
        self.verticalLayout_2.addWidget(self.widget_main)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Месседжер"))
        self.search_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.search_text.setPlaceholderText(_translate("MainWindow", "Поиск"))
        self.sms_label.setText(_translate("MainWindow", "Выберите, кому хотели бы написать"))
        self.send_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.send_text.setPlaceholderText(_translate("MainWindow", "Введите сообщение..."))
